/*
  GROUP-WISE GOOGLE DRIVE CATALOG LINKS — V20
  ------------------------------------------------
  Har GROUP ke saamne double quotes ke andar uska Google Drive / website link paste karein.

  Example:
    "Aayub": "https://drive.google.com/file/d/FILE_ID/view",

  Google Drive sharing ko 'Anyone with the link' rakhein.
  Blank link hone par Download Catalog disabled rahega; Pricelist button current filtered grid ka PDF banayega aur PDF filename selected GROUP name hoga.
  Group matching case, spaces aur punctuation ko ignore karke hoti hai.
*/
window.CATALOG_LINKS = {
  "Aayub": "",
  "Allied": "",
  "Appolo": "",
  "Apristic": "",
  "Ashwamegh": "",
  "Ask": "",
  "Atop": "",
  "Bharti Power": "",
  "Blue Bird": "",
  "Bravo": "",
  "BULLDOG": "",
  "Champion": "",
  "Chander": "",
  "Chener": "",
  "CI": "",
  "Cosmo": "",
  "Crc": "",
  "Dc": "",
  "Delux": "",
  "Elofic": "",
  "Emmbross": "",
  "Fenner": "",
  "GATES": "",
  "Gautam": "",
  "GAUTAM BT": "",
  "GCL": "",
  "GCPA": "",
  "GEEKAY": "",
  "GF": "",
  "GMT": "",
  "GOLD BOSS": "",
  "HALDEX": "",
  "HFL": "",
  "HOLDON": "",
  "IFLEX": "",
  "JHAVERI": "",
  "JM TOMI": "",
  "KBX": "",
  "KD": "",
  "KLIPWEL": "",
  "LAPOX": "",
  "LASCO": "",
  "LGS": "",
  "LOCTITE": "",
  "LUMAN": "",
  "MANN": "",
  "MEKO": "",
  "MK GOLD": "",
  "MONROE": "",
  "NEOLITE": "",
  "NGK": "",
  "NOVEX": "",
  "OEPLUS": "",
  "OLMA": "",
  "OSRAM": "",
  "OXMO": "",
  "PIONEER": "",
  "PIPE ROLL": "",
  "PLATINUM": "",
  "POLY GRIP": "",
  "POOJA": "",
  "PRIMA": "",
  "QH": "",
  "RAICAM": "",
  "RAJNISH": "",
  "RAVI JACK": "",
  "RDS": "",
  "REFEX": "",
  "REMSONS": "",
  "REOX": "",
  "RM": "",
  "RNF": "",
  "ROSE": "",
  "SF": "",
  "SHANCO": "",
  "SORL": "",
  "SPICER": "",
  "ST": "",
  "STAR GOLD": "",
  "STL": "",
  "SUPERLAC": "",
  "SVL": "",
  "Timing Gold": "",
  "Tvs": "",
  "UVAL": "",
  "VALEO": "",
  "VEETHREE": "",
  "VIGEX": "",
  "WAGNER": "",
  "WIX": ""
};
